import { NgModule } from '@angular/core';
import { PreloadAllModules, RouterModule, Routes } from '@angular/router';
// Guards
import { AuthGuard, NoLoginGuard } from "./guards";

const routes: Routes = [
  { path: '', loadChildren: './pages/tabs/tabs.module#TabsPageModule' },
  { path: 'login', loadChildren: './pages/login/login.module#LoginPageModule', canActivate: [NoLoginGuard] },
  { path: 'registro', loadChildren: './pages/registro/registro.module#RegistroPageModule', canActivate: [NoLoginGuard] },
  { path: 'home', loadChildren: './pages/home/home.module#HomePageModule', canActivate: [AuthGuard] },
  { path: 'landing', loadChildren: './pages/landing/landing.module#LandingPageModule' },
  { path: 'agregar', loadChildren: './pages/agregar/agregar.module#AgregarPageModule' },
  { path: 'direcciones', loadChildren: './pages/direcciones/direccion-list/direcciones.module#DireccionesPageModule' },
  { path: 'direccion-add', loadChildren: './pages/direcciones/direccion-add/direccion-add.module#DireccionAddPageModule' },
  { path: 'crear-ubicacion', loadChildren: './pages/crear-ubicacion/crear-ubicacion.module#CrearUbicacionPageModule' },
  { path: 'agregar-direccion', loadChildren: './pages/agregar-direccion/agregar-direccion.module#AgregarDireccionPageModule' },
  { path: 'crear-metodo-pago', loadChildren: './pages/crear-metodo-pago/crear-metodo-pago.module#CrearMetodoPagoPageModule' },
  { path: 'lista-metodo-pago', loadChildren: './pages/lista-metodo-pago/lista-metodo-pago.module#ListaMetodoPagoPageModule' },
  { path: 'perfil', loadChildren: './pages/perfil/perfil.module#PerfilPageModule' },
  { path: 'renovar', loadChildren: './pages/password/renovar/renovar.module#RenovarPageModule' },
  { path: 'solicitar', loadChildren: './pages/password/solicitar/solicitar.module#SolicitarPageModule' },
  { path: 'mensaje', loadChildren: './pages/password/mensaje/mensaje.module#MensajePageModule' },
  { path: 'intro', loadChildren: './pages/intro/intro.module#IntroPageModule' },
  { path: 'direccion-add', loadChildren: './pages/direcciones/direccion-add/direccion-add.module#DireccionAddPageModule' },
  { path: 'direccion-detalle/:id', loadChildren: './pages/direcciones/direccion-detalle/direccion-detalle.module#DireccionDetallePageModule' },
  { path: 'metodo-pago-list', loadChildren: './pages/metodosPago/metodo-pago-list/metodo-pago-list.module#MetodoPagoListPageModule' },
  { path: 'metodo-pago-add', loadChildren: './pages/metodosPago/metodo-pago-add/metodo-pago-add.module#MetodoPagoAddPageModule' },
  { path: 'metodo-pago-detalle/:id', loadChildren: './pages/metodosPago/metodo-pago-detalle/metodo-pago-detalle.module#MetodoPagoDetallePageModule' },
  { path: 'departamento/:id', loadChildren: './pages/departamento/departamento.module#DepartamentoPageModule' },
  { path: 'servicio-list/:id', loadChildren: './pages/servicio/servicio-list/servicio-list.module#ServicioListPageModule' },
  { path: 'profesional-list/:id', loadChildren: './pages/profesional/profesional-list/profesional-list.module#ProfesionalListPageModule' },
  { path: 'profesional-filter', loadChildren: './pages/profesional/profesional-filter/profesional-filter.module#ProfesionalFilterPageModule' },
  { path: 'profesional-result', loadChildren: './pages/profesional/profesional-result/profesional-result.module#ProfesionalResultPageModule' },
  { path: 'profesional-detail', loadChildren: './pages/profesional/profesional-detail/profesional-detail.module#ProfesionalDetailPageModule' },
  { path: 'servicio-req', loadChildren: './pages/servicio/servicio-req/servicio-req.module#ServicioReqPageModule' },
  { path: 'servicio-dir', loadChildren: './pages/servicio/servicio-dir/servicio-dir.module#ServicioDirPageModule' },
  { path: 'servicio-map', loadChildren: './pages/servicio/servicio-map/servicio-map.module#ServicioMapPageModule' },
  { path: 'servicio-pago', loadChildren: './pages/servicio/servicio-pago/servicio-pago.module#ServicioPagoPageModule' },
  { path: 'servicio-con', loadChildren: './pages/servicio/servicio-con/servicio-con.module#ServicioConPageModule' },
  { path: 'orden-servicio-list', loadChildren: './pages/ordenServicio/orden-servicio-list/orden-servicio-list.module#OrdenServicioListPageModule' },
  { path: 'orden-servicio-detail', loadChildren: './pages/ordenServicio/orden-servicio-detail/orden-servicio-detail.module#OrdenServicioDetailPageModule' },
  { path: 'calificacion', loadChildren: './pages/calificacion/calificacion.module#CalificacionPageModule' },
  { path: 'profesional-favorito', loadChildren: './pages/profesional/profesional-favorito/profesional-favorito.module#ProfesionalFavoritoPageModule' },
  { path: 'orden-servicio-filter', loadChildren: './pages/ordenServicio/orden-servicio-filter/orden-servicio-filter.module#OrdenServicioFilterPageModule' },
  { path: 'orden-servicio-result', loadChildren: './pages/ordenServicio/orden-servicio-result/orden-servicio-result.module#OrdenServicioResultPageModule' },
  { path: 'servicio-pago-detalle', loadChildren: './pages/servicio/servicio-pago-detalle/servicio-pago-detalle.module#ServicioPagoDetallePageModule' },
  { path: 'servicio-pago-confirm', loadChildren: './pages/servicio/servicio-pago-confirm/servicio-pago-confirm.module#ServicioPagoConfirmPageModule' },
  { path: 'documento-list', loadChildren: './pages/documentos/documento-list/documento-list.module#DocumentoListPageModule' },
  { path: 'documento-add', loadChildren: './pages/documentos/documento-add/documento-add.module#DocumentoAddPageModule' },
  { path: 'notificacion-list', loadChildren: './pages/notificaciones/notificacion-list/notificacion-list.module#NotificacionListPageModule' },
  { path: 'direccion-mapa', loadChildren: './pages/direcciones/direccion-mapa/direccion-mapa.module#DireccionMapaPageModule' },
  { path: 'orden-servicio-map', loadChildren: './pages/ordenServicio/orden-servicio-map/orden-servicio-map.module#OrdenServicioMapPageModule' },
  { path: 'servicio-foto', loadChildren: './pages/servicio/servicio-foto/servicio-foto.module#ServicioFotoPageModule' },
  { path: 'orden-servicio-img', loadChildren: './pages/ordenServicio/orden-servicio-img/orden-servicio-img.module#OrdenServicioImgPageModule' },
  { path: 'preregistro-home', loadChildren: './pages/preRegistro/preregistro-home/preregistro-home.module#PreRegistroHomePageModule' },
  { path: 'preregistro-datosbasicos', loadChildren: './pages/preRegistro/datos-basicos/datos-basicos.module#DatosBasicosPageModule' },
  { path: 'preregistro-datosespecificos', loadChildren: './pages/preRegistro/datos-especificos/datos-especificos.module#DatosEspecificosPageModule' },
  { path: 'preregistro-datostareastarifas', loadChildren: './pages/preRegistro/datos-tareas-tarifas/datos-tareas-tarifas.module#DatosTareasTarifasPageModule' },
  { path: 'documento-detalle', loadChildren: './pages/documentos/documento-detalle/documento-detalle.module#DocumentoDetallePageModule' },
  { path: 'orden-servicio-select', loadChildren: './pages/ordenServicio/orden-servicio-select/orden-servicio-select.module#OrdenServicioSelectPageModule' },
  { path: 'tarea-list', loadChildren: './pages/tareas/tarea-list/tarea-list.module#TareaListPageModule' },
  { path: 'calificacion-list', loadChildren: './pages/calificacion/calificacion-list/calificacion-list.module#CalificacionListPageModule' },  
  { path: 'datos-metodos-pago', loadChildren: './pages/preRegistro/datos-metodos-pago/datos-metodos-pago.module#DatosMetodosPagoPageModule' },
  { path: 'portafolio-list', loadChildren: './pages/portafolio/portafolio-list/portafolio-list.module#PortafolioListPageModule' },
  { path: 'portafolio-add', loadChildren: './pages/portafolio/portafolio-add/portafolio-add.module#PortafolioAddPageModule' },
  { path: 'portafolio-detalle', loadChildren: './pages/portafolio/portafolio-detalle/portafolio-detalle.module#PortafolioDetallePageModule' },
  { path: 'profesional-portafolio', loadChildren: './pages/profesional/profesional-portafolio/profesional-portafolio.module#ProfesionalPortafolioPageModule' },
  { path: 'perfil-edit', loadChildren: './pages/perfil/perfil-edit/perfil-edit.module#PerfilEditPageModule' },
  { path: 'perfil-servicios', loadChildren: './pages/perfil/perfil-servicios/perfil-servicios.module#PerfilServiciosPageModule' },
];
@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })
  ],
  exports: [RouterModule]
})
export class AppRoutingModule { } 
